---
- hosts: all
  become: true
  tasks:
    - name: Fetch changes from git repository
      git:
        repo: https://github.com/School-58-IT-gen-2/quest-hub-app.git
        dest: /projects/dnd/quest-hub-app
        fetch: yes
        branch: development

    - name: Pull changes from git repository
      git:
        repo: https://github.com/School-58-IT-gen-2/quest-hub-app.git
        dest: /projects/dnd/quest-hub-app
        update: yes
        branch: development
    
    - name: Build Docker image
      docker_image:
        name: quest_hub_app:0.0.2
        path: /projects/dnd/quest-hub-app/Dockerfile


    - name: Run docker-compose up
      command: docker-compose up -d --force-recreate
      args:
        chdir: /projects/dnd/quest-hub-app


