---
- hosts: questhub.pro
  become: true
  tasks:

    
    - name: Build Docker image
      docker_image:
        name: quest_hub_app:0.0.2
        path: /projects/dnd/quest-hub-app/Dockerfile


    - name: Run docker-compose up
      command: docker-compose up -d --force-recreate
      args:
        chdir: /projects/dnd/quest-hub-app


