- name: Run alert_bot
  hosts: all
  tasks:
  
  - name: Entering virtual environment
    shell: source /projects/dnd/ansible_env/bin/activate
    args:
      executable: /bin/bash

  - name: Install dependencies
    command: pip install aiogram && pip install asyncio

  - name: Run_alert_script
    command: python3 /projects/dnd/quest-hub-app/scripts/send_telegram_alert.py