name: Ansible Playbook Execution

on:
  push:
    branches:
      - cd
  workflow_dispatch:
jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install ansible

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/private_key.pem
          chmod 600 ~/.ssh/private_key.pem
      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_HOST }}" > ~/inventory/hosts.ini
          chmod 600 ~/inventory/hosts.ini
      - name: Run Ansible playbook
        run: |
          ansible-playbook -i ~/inventory/hosts.ini ~/playbooks/deploy_web_server.yml --private-key ~/.ssh/private_key.pem -u ${{ secrets.ANSIBLE_USER }}