name: Run Tests

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main

jobs:
  test:
    name: Install & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: 
          python -m unittest tests\adapters\db_source_test.py