name: Run Tests

on:
  pull_request:
    branches:
      - development
      - main
      - feature/ci
      - tryflake8
      - git_actions_test
      - ceo_testirovki_branch

jobs:
  test:
    name: Autotest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: upgrate pip
        run: 
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: 
          pip install -r requirements.txt

      - name: Construct .env
        run:
          echo "FASTAPI_HOST=${{secrets.FASTAPI_HOST}}" >> .env & echo "FASTAPI_PORT=${{secrets.FASTAPI_PORT}}" >> .env & echo "SUPABASE_URL=${{secrets.SUPABASE_URL}}" >> .env & echo "SUPABASE_KEY=${{secrets.SUPABASE_KEY}}" >> .env

      - name: Run CI tests
        run: 
          python -m unittest tests/adapters/db_source_test.py
  
  lint:
    name: Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: upgrate pip
        run: 
          python -m pip install --upgrade pip
      
      - name: Install flake8
        run:
          python -m pip install flake8 

      - name: Flake8 tests
        run:
          flake8 